# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/battery_detect_withGUI/src/View/bubble_detect_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2212, 787)
        MainWindow.setStyleSheet("/*For all window settings*/\n"
"*{\n"
"    border: none;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff; /*text color*/\n"
"}\n"
"\n"
"QRadioButton {\n"
"    background-color: transparent;\n"
"    color:                  white;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.5);\n"
"}\n"
"\n"
"QPushButton:hover:pressed { color: rgb(23, 237, 255); }\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: rgb(46, 52, 54);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"\n"
"}\n"
"\n"
"/* rightMenu*/\n"
"#rightMenuContainer{\n"
"    background-color: #2c313c;\n"
"    border: 3px solid white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#showText_Info{\n"
"    padding: 6px 0px;\n"
"    border-bottom-width: 3px;\n"
"    border-bottom-style: solid;\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#Calib_info_container{\n"
"    border: 3px solid white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#Battery_info_container{\n"
"    border: 3px solid white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#bubbleBtn{\n"
"    border: 6px solid white groove #242424;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#calibratedBtn{\n"
"    border: 6px solid white groove #242424;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#cameraBtn{\n"
"    border: 6px solid white groove #242424;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#emergencyBtn{\n"
"    border: 6px solid white groove #242424;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#stopBtn{\n"
"    border: 6px solid white groove #242424;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#parameterBtn{\n"
"    border: 6px solid white groove #242424;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#show_coord_Info{\n"
"    padding: 6px 0px;\n"
"    border-bottom-width: 3px;\n"
"    border-bottom-style: solid;\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* CenterMenu */\n"
"#centerMenuContainer{\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"\n"
"/* leftMenu */\n"
"\n"
"\n"
"#leftMenuSubContainer{\n"
"    background-color: #2c313c;\n"
"    border: 3px solid white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#leftMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#leftMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#showText{\n"
"    padding: 6px 0px;\n"
"    border-bottom-width: 3px;\n"
"    border-bottom-style: solid;\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#BubbleInfoOnBtn::indicator:checked , #BubbleBoxOnBtn::indicator:checked {\n"
"    background-color: green;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"#BubbleInfoOffBtn::indicator:checked , #BubbleBoxOffBtn::indicator:checked {\n"
"    background-color: red;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"#leftMenuSubContainer QRadioButton::indicator:unchecked {\n"
"    background-color:       transparent;\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QPushButton:hover[objectName^=\"bubbleBoxBtn\"],\n"
"QPushButton:hover[objectName^=\"bubbleInfoBtn\"]{\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"/* rightMenu */\n"
"#rightMenuSubContainer{\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"#rightMenuSubContainer QRadioButton::indicator:unchecked {\n"
"    background-color:       transparent;\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"#bubbleDetectCheckYesBtn::indicator:checked , #calibrationCheckYesBtn::indicator:checked {\n"
"    background-color: green;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"#bubbleDetectCheckNoBtn::indicator:checked , #calibrationCheckNoBtn::indicator:checked {\n"
"    background-color: red;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"#showStatusText\n"
"{\n"
"    border-bottom-width: 3px;\n"
"    border-bottom-style: solid;\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#trigBtnText\n"
"{\n"
"    border-bottom-width: 3px;\n"
"    border-bottom-style: solid;\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* copyright label text size*/\n"
"#copyrightLabel\n"
"{\n"
"    font-size: 8pt;\n"
"}")
        self.centralwidgetf = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidgetf.sizePolicy().hasHeightForWidth())
        self.centralwidgetf.setSizePolicy(sizePolicy)
        self.centralwidgetf.setAutoFillBackground(False)
        self.centralwidgetf.setObjectName("centralwidgetf")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidgetf)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QtWidgets.QWidget(self.centralwidgetf)
        self.leftMenuContainer.setMaximumSize(QtCore.QSize(180, 16777215))
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.leftMenuSubContainer = QtWidgets.QWidget(self.leftMenuContainer)
        self.leftMenuSubContainer.setObjectName("leftMenuSubContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.leftMenuSubContainer)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.showText = QtWidgets.QLabel(self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showText.sizePolicy().hasHeightForWidth())
        self.showText.setSizePolicy(sizePolicy)
        self.showText.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.showText.setFont(font)
        self.showText.setScaledContents(False)
        self.showText.setAlignment(QtCore.Qt.AlignCenter)
        self.showText.setObjectName("showText")
        self.verticalLayout_5.addWidget(self.showText)
        self.cameraBtn = QtWidgets.QPushButton(self.leftMenuSubContainer)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cameraBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cameraBtn.setIcon(icon)
        self.cameraBtn.setIconSize(QtCore.QSize(24, 24))
        self.cameraBtn.setObjectName("cameraBtn")
        self.verticalLayout_5.addWidget(self.cameraBtn)
        self.calibratedBtn = QtWidgets.QPushButton(self.leftMenuSubContainer)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.calibratedBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/chessboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calibratedBtn.setIcon(icon1)
        self.calibratedBtn.setIconSize(QtCore.QSize(24, 24))
        self.calibratedBtn.setObjectName("calibratedBtn")
        self.verticalLayout_5.addWidget(self.calibratedBtn)
        self.parameterBtn = QtWidgets.QPushButton(self.leftMenuSubContainer)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.parameterBtn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./src/battery_detect_withGUI/src/View/../../../../../../../.designer/Resource/icon/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/settings.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.parameterBtn.setIcon(icon2)
        self.parameterBtn.setIconSize(QtCore.QSize(24, 24))
        self.parameterBtn.setObjectName("parameterBtn")
        self.verticalLayout_5.addWidget(self.parameterBtn)
        self.bubbleBtn = QtWidgets.QPushButton(self.leftMenuSubContainer)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.bubbleBtn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/self_made/self_made/battery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bubbleBtn.setIcon(icon3)
        self.bubbleBtn.setIconSize(QtCore.QSize(24, 24))
        self.bubbleBtn.setObjectName("bubbleBtn")
        self.verticalLayout_5.addWidget(self.bubbleBtn)
        self.stopBtn = QtWidgets.QPushButton(self.leftMenuSubContainer)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.stopBtn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/pause.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopBtn.setIcon(icon4)
        self.stopBtn.setObjectName("stopBtn")
        self.verticalLayout_5.addWidget(self.stopBtn)
        self.emergencyBtn = QtWidgets.QPushButton(self.leftMenuSubContainer)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.emergencyBtn.setFont(font)
        self.emergencyBtn.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./src/battery_detect_withGUI/src/View/../../../../../../../.designer/Resource/icon/alert-triangle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/alert-triangle.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.emergencyBtn.setIcon(icon5)
        self.emergencyBtn.setIconSize(QtCore.QSize(24, 24))
        self.emergencyBtn.setObjectName("emergencyBtn")
        self.verticalLayout_5.addWidget(self.emergencyBtn)
        self.widget_2 = QtWidgets.QWidget(self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(500, 500))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.company_iconLabel = QtWidgets.QLabel(self.widget_2)
        self.company_iconLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.company_iconLabel.sizePolicy().hasHeightForWidth())
        self.company_iconLabel.setSizePolicy(sizePolicy)
        self.company_iconLabel.setMaximumSize(QtCore.QSize(400, 400))
        self.company_iconLabel.setText("")
        self.company_iconLabel.setPixmap(QtGui.QPixmap(":/self_made/self_made/file.jpg"))
        self.company_iconLabel.setScaledContents(True)
        self.company_iconLabel.setWordWrap(False)
        self.company_iconLabel.setOpenExternalLinks(False)
        self.company_iconLabel.setObjectName("company_iconLabel")
        self.verticalLayout_6.addWidget(self.company_iconLabel)
        self.IRIS_iconLabel = QtWidgets.QLabel(self.widget_2)
        self.IRIS_iconLabel.setText("")
        self.IRIS_iconLabel.setPixmap(QtGui.QPixmap(":/self_made/self_made/iris.png"))
        self.IRIS_iconLabel.setScaledContents(True)
        self.IRIS_iconLabel.setObjectName("IRIS_iconLabel")
        self.verticalLayout_6.addWidget(self.IRIS_iconLabel)
        self.copyrightLabel = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.copyrightLabel.setFont(font)
        self.copyrightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.verticalLayout_6.addWidget(self.copyrightLabel)
        self.verticalLayout_5.addWidget(self.widget_2, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.leftMenuSubContainer)
        self.horizontalLayout.addWidget(self.leftMenuContainer)
        self.centerMenuContainer = QtWidgets.QWidget(self.centralwidgetf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerMenuContainer.sizePolicy().hasHeightForWidth())
        self.centerMenuContainer.setSizePolicy(sizePolicy)
        self.centerMenuContainer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centerMenuContainer.setToolTip("")
        self.centerMenuContainer.setStatusTip("")
        self.centerMenuContainer.setObjectName("centerMenuContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centerMenuContainer)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.centerMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cameraLabel = QtWidgets.QLabel(self.widget_4)
        self.cameraLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraLabel.sizePolicy().hasHeightForWidth())
        self.cameraLabel.setSizePolicy(sizePolicy)
        self.cameraLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraLabel.setMaximumSize(QtCore.QSize(1500, 1000))
        self.cameraLabel.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cameraLabel.setFont(font)
        self.cameraLabel.setToolTip("")
        self.cameraLabel.setStatusTip("")
        self.cameraLabel.setScaledContents(True)
        self.cameraLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraLabel.setObjectName("cameraLabel")
        self.verticalLayout_4.addWidget(self.cameraLabel)
        self.verticalLayout_3.addWidget(self.widget_4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.centerMenuContainer)
        self.rightMenuContainer = QtWidgets.QWidget(self.centralwidgetf)
        self.rightMenuContainer.setMaximumSize(QtCore.QSize(180, 16777215))
        self.rightMenuContainer.setObjectName("rightMenuContainer")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.rightMenuContainer)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.showText_Info = QtWidgets.QLabel(self.rightMenuContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.showText_Info.setFont(font)
        self.showText_Info.setObjectName("showText_Info")
        self.verticalLayout_14.addWidget(self.showText_Info, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Calib_info_container = QtWidgets.QWidget(self.rightMenuContainer)
        self.Calib_info_container.setObjectName("Calib_info_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Calib_info_container)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Y_container = QtWidgets.QWidget(self.Calib_info_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y_container.sizePolicy().hasHeightForWidth())
        self.Y_container.setSizePolicy(sizePolicy)
        self.Y_container.setMinimumSize(QtCore.QSize(3, 3))
        self.Y_container.setObjectName("Y_container")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Y_container)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Y_label_Value = QtWidgets.QWidget(self.Y_container)
        self.Y_label_Value.setObjectName("Y_label_Value")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Y_label_Value)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.circle_text = QtWidgets.QLabel(self.Y_label_Value)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.circle_text.setFont(font)
        self.circle_text.setObjectName("circle_text")
        self.horizontalLayout_15.addWidget(self.circle_text)
        self.circle_text_print = QtWidgets.QLabel(self.Y_label_Value)
        self.circle_text_print.setText("")
        self.circle_text_print.setObjectName("circle_text_print")
        self.horizontalLayout_15.addWidget(self.circle_text_print)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.three_L_text = QtWidgets.QLabel(self.Y_label_Value)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.three_L_text.setFont(font)
        self.three_L_text.setObjectName("three_L_text")
        self.horizontalLayout_14.addWidget(self.three_L_text)
        self.three_L_text_print = QtWidgets.QLabel(self.Y_label_Value)
        self.three_L_text_print.setText("")
        self.three_L_text_print.setObjectName("three_L_text_print")
        self.horizontalLayout_14.addWidget(self.three_L_text_print)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.AL_text = QtWidgets.QLabel(self.Y_label_Value)
        self.AL_text.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AL_text.sizePolicy().hasHeightForWidth())
        self.AL_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AL_text.setFont(font)
        self.AL_text.setToolTip("")
        self.AL_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AL_text.setObjectName("AL_text")
        self.horizontalLayout_13.addWidget(self.AL_text)
        self.AL_text_print = QtWidgets.QLabel(self.Y_label_Value)
        self.AL_text_print.setText("")
        self.AL_text_print.setObjectName("AL_text_print")
        self.horizontalLayout_13.addWidget(self.AL_text_print)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Li_text = QtWidgets.QLabel(self.Y_label_Value)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Li_text.setFont(font)
        self.Li_text.setObjectName("Li_text")
        self.horizontalLayout_12.addWidget(self.Li_text)
        self.Li_text_print = QtWidgets.QLabel(self.Y_label_Value)
        self.Li_text_print.setText("")
        self.Li_text_print.setObjectName("Li_text_print")
        self.horizontalLayout_12.addWidget(self.Li_text_print)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.NICD_text = QtWidgets.QLabel(self.Y_label_Value)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NICD_text.setFont(font)
        self.NICD_text.setObjectName("NICD_text")
        self.horizontalLayout_8.addWidget(self.NICD_text)
        self.NICD_text_print = QtWidgets.QLabel(self.Y_label_Value)
        self.NICD_text_print.setText("")
        self.NICD_text_print.setObjectName("NICD_text_print")
        self.horizontalLayout_8.addWidget(self.NICD_text_print)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.NIMH_text = QtWidgets.QLabel(self.Y_label_Value)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NIMH_text.setFont(font)
        self.NIMH_text.setObjectName("NIMH_text")
        self.horizontalLayout_7.addWidget(self.NIMH_text)
        self.NIMH_text_print = QtWidgets.QLabel(self.Y_label_Value)
        self.NIMH_text_print.setText("")
        self.NIMH_text_print.setObjectName("NIMH_text_print")
        self.horizontalLayout_7.addWidget(self.NIMH_text_print)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ZnMn_text = QtWidgets.QLabel(self.Y_label_Value)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ZnMn_text.setFont(font)
        self.ZnMn_text.setObjectName("ZnMn_text")
        self.horizontalLayout_6.addWidget(self.ZnMn_text)
        self.ZnMn_text_print = QtWidgets.QLabel(self.Y_label_Value)
        self.ZnMn_text_print.setText("")
        self.ZnMn_text_print.setObjectName("ZnMn_text_print")
        self.horizontalLayout_6.addWidget(self.ZnMn_text_print)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.square_text = QtWidgets.QLabel(self.Y_label_Value)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.square_text.setFont(font)
        self.square_text.setObjectName("square_text")
        self.horizontalLayout_2.addWidget(self.square_text)
        self.square_text_print = QtWidgets.QLabel(self.Y_label_Value)
        self.square_text_print.setText("")
        self.square_text_print.setObjectName("square_text_print")
        self.horizontalLayout_2.addWidget(self.square_text_print)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.package_text = QtWidgets.QLabel(self.Y_label_Value)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.package_text.setFont(font)
        self.package_text.setObjectName("package_text")
        self.horizontalLayout_3.addWidget(self.package_text)
        self.package_text_print = QtWidgets.QLabel(self.Y_label_Value)
        self.package_text_print.setText("")
        self.package_text_print.setTextFormat(QtCore.Qt.PlainText)
        self.package_text_print.setObjectName("package_text_print")
        self.horizontalLayout_3.addWidget(self.package_text_print)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.Y_y_coord_value_label = QtWidgets.QTextEdit(self.Y_label_Value)
        self.Y_y_coord_value_label.setObjectName("Y_y_coord_value_label")
        self.verticalLayout_8.addWidget(self.Y_y_coord_value_label)
        self.horizontalLayout_4.addWidget(self.Y_label_Value)
        self.verticalLayout.addWidget(self.Y_container)
        self.O_point_container = QtWidgets.QWidget(self.Calib_info_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.O_point_container.sizePolicy().hasHeightForWidth())
        self.O_point_container.setSizePolicy(sizePolicy)
        self.O_point_container.setMinimumSize(QtCore.QSize(3, 3))
        self.O_point_container.setObjectName("O_point_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.O_point_container)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout.addWidget(self.O_point_container)
        self.verticalLayout_14.addWidget(self.Calib_info_container)
        self.show_coord_info = QtWidgets.QLabel(self.rightMenuContainer)
        self.show_coord_info.setObjectName("show_coord_info")
        self.verticalLayout_14.addWidget(self.show_coord_info, 0, QtCore.Qt.AlignHCenter)
        self.Battery_info_container = QtWidgets.QWidget(self.rightMenuContainer)
        self.Battery_info_container.setObjectName("Battery_info_container")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.Battery_info_container)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.O_point_container_3 = QtWidgets.QWidget(self.Battery_info_container)
        self.O_point_container_3.setObjectName("O_point_container_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.O_point_container_3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.O_point_label_3 = QtWidgets.QLabel(self.O_point_container_3)
        self.O_point_label_3.setObjectName("O_point_label_3")
        self.horizontalLayout_11.addWidget(self.O_point_label_3, 0, QtCore.Qt.AlignLeft)
        self.O_point_label_Value_3 = QtWidgets.QWidget(self.O_point_container_3)
        self.O_point_label_Value_3.setObjectName("O_point_label_Value_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.O_point_label_Value_3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.O_point_x_coord_value_label_3 = QtWidgets.QLabel(self.O_point_label_Value_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.O_point_x_coord_value_label_3.sizePolicy().hasHeightForWidth())
        self.O_point_x_coord_value_label_3.setSizePolicy(sizePolicy)
        self.O_point_x_coord_value_label_3.setText("")
        self.O_point_x_coord_value_label_3.setObjectName("O_point_x_coord_value_label_3")
        self.verticalLayout_18.addWidget(self.O_point_x_coord_value_label_3)
        self.O_point_y_coord_value_label_3 = QtWidgets.QLabel(self.O_point_label_Value_3)
        self.O_point_y_coord_value_label_3.setText("")
        self.O_point_y_coord_value_label_3.setObjectName("O_point_y_coord_value_label_3")
        self.verticalLayout_18.addWidget(self.O_point_y_coord_value_label_3)
        self.horizontalLayout_11.addWidget(self.O_point_label_Value_3)
        self.verticalLayout_15.addWidget(self.O_point_container_3)
        self.X_container_3 = QtWidgets.QWidget(self.Battery_info_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_container_3.sizePolicy().hasHeightForWidth())
        self.X_container_3.setSizePolicy(sizePolicy)
        self.X_container_3.setObjectName("X_container_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.X_container_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.X_label_3 = QtWidgets.QLabel(self.X_container_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_label_3.sizePolicy().hasHeightForWidth())
        self.X_label_3.setSizePolicy(sizePolicy)
        self.X_label_3.setObjectName("X_label_3")
        self.horizontalLayout_9.addWidget(self.X_label_3, 0, QtCore.Qt.AlignLeft)
        self.X_label_Value_3 = QtWidgets.QWidget(self.X_container_3)
        self.X_label_Value_3.setObjectName("X_label_Value_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.X_label_Value_3)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.X_x_coord_value_label_3 = QtWidgets.QLabel(self.X_label_Value_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_x_coord_value_label_3.sizePolicy().hasHeightForWidth())
        self.X_x_coord_value_label_3.setSizePolicy(sizePolicy)
        self.X_x_coord_value_label_3.setText("")
        self.X_x_coord_value_label_3.setObjectName("X_x_coord_value_label_3")
        self.verticalLayout_16.addWidget(self.X_x_coord_value_label_3)
        self.X_y_coord_value_label_3 = QtWidgets.QLabel(self.X_label_Value_3)
        self.X_y_coord_value_label_3.setText("")
        self.X_y_coord_value_label_3.setObjectName("X_y_coord_value_label_3")
        self.verticalLayout_16.addWidget(self.X_y_coord_value_label_3)
        self.horizontalLayout_9.addWidget(self.X_label_Value_3)
        self.verticalLayout_15.addWidget(self.X_container_3)
        self.Y_container_3 = QtWidgets.QWidget(self.Battery_info_container)
        self.Y_container_3.setObjectName("Y_container_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.Y_container_3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Y_label_3 = QtWidgets.QLabel(self.Y_container_3)
        self.Y_label_3.setObjectName("Y_label_3")
        self.horizontalLayout_10.addWidget(self.Y_label_3, 0, QtCore.Qt.AlignLeft)
        self.Y_label_Value_3 = QtWidgets.QWidget(self.Y_container_3)
        self.Y_label_Value_3.setObjectName("Y_label_Value_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.Y_label_Value_3)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Y_x_coord_value_label_3 = QtWidgets.QLabel(self.Y_label_Value_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y_x_coord_value_label_3.sizePolicy().hasHeightForWidth())
        self.Y_x_coord_value_label_3.setSizePolicy(sizePolicy)
        self.Y_x_coord_value_label_3.setText("")
        self.Y_x_coord_value_label_3.setObjectName("Y_x_coord_value_label_3")
        self.verticalLayout_17.addWidget(self.Y_x_coord_value_label_3)
        self.Y_y_coord_value_label_3 = QtWidgets.QLabel(self.Y_label_Value_3)
        self.Y_y_coord_value_label_3.setText("")
        self.Y_y_coord_value_label_3.setObjectName("Y_y_coord_value_label_3")
        self.verticalLayout_17.addWidget(self.Y_y_coord_value_label_3)
        self.horizontalLayout_10.addWidget(self.Y_label_Value_3)
        self.verticalLayout_15.addWidget(self.Y_container_3)
        self.verticalLayout_14.addWidget(self.Battery_info_container)
        self.horizontalLayout.addWidget(self.rightMenuContainer, 0, QtCore.Qt.AlignRight)
        MainWindow.setCentralWidget(self.centralwidgetf)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showText.setText(_translate("MainWindow", "操作"))
        self.cameraBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#fce94f;\">相機畫面測試，確認相機當前拍攝位置與範圍是否符合預期</span></p></body></html>"))
        self.cameraBtn.setText(_translate("MainWindow", "相機調整"))
        self.calibratedBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#fce94f;\">校正相機座標，並獲取座標軸資訊</span></p></body></html>"))
        self.calibratedBtn.setText(_translate("MainWindow", "座標校正"))
        self.parameterBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#fce94f;\">調整專案參數</span></p></body></html>"))
        self.parameterBtn.setText(_translate("MainWindow", "參數調整"))
        self.bubbleBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#fce94f;\">執行夾取電池專案</span></p></body></html>"))
        self.bubbleBtn.setText(_translate("MainWindow", "夾取電池"))
        self.stopBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#fce94f;\">專案停止，手臂回到原點，並顯示統計數據</span></p></body></html>"))
        self.stopBtn.setText(_translate("MainWindow", "停止夾取"))
        self.emergencyBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#fce94f;\">停止所有專案，且手臂緊急停止在當前位置</span></p></body></html>"))
        self.emergencyBtn.setText(_translate("MainWindow", "緊急停止"))
        self.copyrightLabel.setText(_translate("MainWindow", "Copyright by NSYSU-IRIS Lab"))
        self.cameraLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">操作教學</span></p><p align=\"center\"><br/></p><p align=\"justify\">1. <span style=\" font-weight:600;\">相機調整</span>：此功能用於確認相機拍攝範圍是符合預期，若不符合則手動調整相機位置使畫面恰好拍攝到輸送帶中央。</p><p align=\"justify\">2. <span style=\" font-weight:600;\">座標校正</span>：若有移動到相機就必須進行座標校正，會先跳出一個手臂校正的提示，請先在輸送帶上放上QR code，</p><p align=\"justify\">之後用手臂對到QR code的原點,X點,Y點定出新座標系，確保不會再移動鏡頭與QR code後按下手臂校正提示的OK，</p><p align=\"justify\">按下OK後程式會自動抓取QR code三點當作新座標軸，並在10秒後自動結束校正功能。</p><p align=\"justify\">3. <span style=\" font-weight:600;\">參數調整</span>：調整程式參數。</p><p align=\"justify\">4. <span style=\" font-weight:600;\">夾取電池</span>：執行夾取專案。</p><p align=\"justify\">5. <span style=\" font-weight:600;\">停止夾取</span>：停止程式，手臂回到HOME位置，並顯示統計數據。</p><p align=\"justify\">6. <span style=\" font-weight:600;\">緊急停止</span>：停止程式，手臂停在當前位置。</p></body></html>"))
        self.showText_Info.setText(_translate("MainWindow", "夾取數量"))
        self.circle_text.setText(_translate("MainWindow", "circle:"))
        self.three_L_text.setText(_translate("MainWindow", "3L:"))
        self.AL_text.setText(_translate("MainWindow", "Alkaline:"))
        self.Li_text.setText(_translate("MainWindow", "LiOnce:"))
        self.NICD_text.setText(_translate("MainWindow", "NICD:"))
        self.NIMH_text.setText(_translate("MainWindow", "NIMH:"))
        self.ZnMn_text.setText(_translate("MainWindow", "ZnMn:"))
        self.square_text.setText(_translate("MainWindow", "square:"))
        self.package_text.setText(_translate("MainWindow", "package:"))
        self.show_coord_info.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">座標資訊</span></p></body></html>"))
        self.O_point_label_3.setText(_translate("MainWindow", "O: "))
        self.X_label_3.setText(_translate("MainWindow", "X: "))
        self.Y_label_3.setText(_translate("MainWindow", "Y: "))
import resource_for_mirdc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
